### PR TITLE
PCCEditor 2: Array values show # of elements | Interpreter 2: Can now delete 4 byte array element

### PR DESCRIPTION
**Pull request by Mgamerz**
PCCEditor 2: ArrayProperties now list the number of elements that the header data indicates. This fixes the "0" or random number that is currently already there.

Interpreter2: You can now click on an arrayleaf node and click "Delete Array Element" to remove a 4 byte chunk of memory at that address. The array size and length are updated and the memory ME3Explorer is holding for that export is updated.

### CODE REVIEW

**Comment by Mgamerz** [comment]
PCCEditor 2 UI:
image

# 

Interpreter 2 Array
Before deletion:
image

After deletion:
image

**Comment by SirCxyrtyx** [comment]
If the array is a child of a structprop or an arrayprop, will this update the parent's size as well?

**Comment by Mgamerz** [comment]
Did not account for that. Can probably bubble it up, will look at it tomorrow.

**Comment by Mgamerz** [comment]
Updated code with bubble-up size changes. Using this tool assumes you are using elements aligned to a 4-byte boundary (or a multiple of that). I have seen one that has a 6 byte boundary (LODLevels), which when using this, doesn't work properly, but I think this is an edge case. Perhaps should find the byte boundary based on the size / item count... for another day.

**Pull request merged**
